### ISSUE TITLE
Measurement report and stream broken on Python3.4

### ISSUE THREAD

**Issue by oskar456** [RIPE-NCC/ripe-atlas-tools#105]
I'm trying to display report for a measurement using stable RIPE Atlas tools installed inside virtualenv on a Gentoo box. When I ask for a report, the tool crashes:

    $ ripe-atlas report 1695915
    
    RIPE Atlas Report for Measurement #1695915
    ===================================================
    Anchoring Measurement: Traceroute IPv6 for anchor cz-prg-as2852.anchors.atlas.ripe.net
    
    Traceback (most recent call last):
      File "/home/oskar/Downloads/atlas/venv/bin/ripe-atlas", line 94, in <module>
        sys.exit(RipeAtlas().main())
      File "/home/oskar/Downloads/atlas/venv/bin/ripe-atlas", line 85, in main
        cmd.run()
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/commands/report.py", line 128, in run
        payload=results
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 80, in render
        self._smart_render(self.payload)
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 100, in _smart_render
        for line in self._get_rendered_results(data):
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 87, in _get_rendered_results
        for sagan in data:
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 42, in __iter__
        for sagan in self._attach_probes(sagans):
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 60, in _attach_probes
        [(p.id, p) for p in Probe.get_many(s.probe_id for s in sagans)]
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/probes/__init__.py", line 40, in get_many
        probe = cache.get("probe:{}".format(pk))
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/cache.py", line 46, in get
        expires, value = pickle.loads(self._db[key])
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 1: ordinal not in range(128)
    

Different crash occurs for the live streaming:

    $ ripe-atlas stream 1695915
    Traceback (most recent call last):
      File "/home/oskar/Downloads/atlas/venv/bin/ripe-atlas", line 94, in <module>
        sys.exit(RipeAtlas().main())
      File "/home/oskar/Downloads/atlas/venv/bin/ripe-atlas", line 85, in main
        cmd.run()
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/commands/stream.py", line 49, in run
        self.arguments.measurement_id
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/streaming.py", line 44, in stream
        stream.timeout(self.timeout)
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/cousteau/stream.py", line 62, in timeout
        self.socketIO.wait()
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/socketIO_client/__init__.py", line 232, in wait
        self._process_packets()
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/socketIO_client/__init__.py", line 256, in _process_packets
        self._process_packet(engineIO_packet)
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/socketIO_client/__init__.py", line 461, in _process_packet
        delegate(socketIO_packet_data, namespace)
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/socketIO_client/__init__.py", line 482, in _on_event
        namespace._find_packet_callback(event)(*args)
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/streaming.py", line 32, in on_result_response
        on_malformation=Result.ACTION_IGNORE
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/renderers/traceroute.py", line 24, in on_result
        "ms  ".join(["{0:8}".format(rtt) for rtt in rtts])
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/renderers/traceroute.py", line 24, in <listcomp>
        "ms  ".join(["{0:8}".format(rtt) for rtt in rtts])
    TypeError: non-empty format string passed to object.__format__
    
Using virtualenv with Python 2.7.10 works without error.

**Comment by danielquinn** [comment]
If both of these instances are running on the same machine, then that's probably the problem: the toolkit employs a simple caching framework that uses a file in `${HOME}/.config/ripe-atlas-tools/cache.db*`.  If you run the script once using Python2 and then again later with Python3, the native objects that are cached won't play nice with what's there and Bad Things will happen.

To work around this, simply delete the cache file(s) and try again with Python3.  If the problem persists, then it's something we can look at, but from the looks of your traceback there, I'm thinking this is the problem.

I suppose we could setup the cache to use a different file between Py2 and Py3, but honestly, I didn't think that this would happen in the wild ;-)

Also, nice choice of distro there.  It's always nice to meet a fellow Gentooer.

**Comment by oskar456** [comment]
@danielquinn You are right, the first traceback was caused by cache records from the previous test with Py2. However, after cleaning the cache, it will crash anyway:

    $ ripe-atlas report 1695915
    
    RIPE Atlas Report for Measurement #1695915
    ===================================================
    Anchoring Measurement: Traceroute IPv6 for anchor cz-prg-as2852.anchors.atlas.ripe.net
    
    Traceback (most recent call last):
      File "/home/oskar/Downloads/atlas/venv/bin/ripe-atlas", line 94, in <module>
        sys.exit(RipeAtlas().main())
      File "/home/oskar/Downloads/atlas/venv/bin/ripe-atlas", line 85, in main
        cmd.run()
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/commands/report.py", line 128, in run
        payload=results
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 80, in render
        self._smart_render(self.payload)
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 100, in _smart_render
        for line in self._get_rendered_results(data):
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/helpers/rendering.py", line 88, in _get_rendered_results
        yield self.renderer.on_result(sagan)
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/renderers/traceroute.py", line 24, in on_result
        "ms  ".join(["{0:8}".format(rtt) for rtt in rtts])
      File "/home/oskar/Downloads/atlas/venv/lib/python3.4/site-packages/ripe/atlas/tools/renderers/traceroute.py", line 24, in <listcomp>
        "ms  ".join(["{0:8}".format(rtt) for rtt in rtts])
    TypeError: non-empty format string passed to object.__format__

This is the crash I've seen at the begining, before I tested whether it is also broken on Py2, which is not.

**Comment by danielquinn** [comment]
Ah I see it now.  Python3 doesn't like casting `None` to a string so it explodes, unlike Python2, which happily returns `"None"`.  Alright, I'll patch this up, add a test for it, and when it's merged into master this ticket will close and you should get a notification.
