### ISSUE TITLE
pip3 install --user ripe-atlas-tools failure

### ISSUE THREAD

**Issue by shane-kerr** [RIPE-NCC/ripe-atlas-tools#165]
Using Debian testing:
```
$ pip3 install --user ripe-atlas-tools
  .
  .
  .
Exception:
Traceback (most recent call last):
  File "/home/shane/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/shane/.local/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/shane/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/home/shane/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/shane/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/home/shane/.local/lib/python3.5/site-packages/pip/wheel.py", line 348, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: ripe-atlas-tools .dist-info directory not found
```

I didn't create a `virtualenv` or anything.

**Comment by shane-kerr** [comment]
Fixed by using:

    $ pip3 install --user ripe.atlas.tools

Seems to work!
