### ISSUE TITLE
_gdbm.error: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by AlfredArouna** [RIPE-NCC/ripe-atlas-tools#177]
I have this error while trying to get measurement result. I install from source (https://ripe-atlas-tools.readthedocs.io/en/latest/installation.html#from-github) on Manjaro Linux.

% lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	16.10
Codename:	Fringilla

% ripe-atlas report 1001
Traceback (most recent call last):
  File "/usr/bin/ripe-atlas", line 151, in <module>
    sys.exit(RipeAtlas().main())
  File "/usr/bin/ripe-atlas", line 146, in main
    cmd.run()
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/commands/report.py", line 205, in run
    Rendering(renderer=renderer, payload=results).render()
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/helpers/rendering.py", line 100, in render
    self._smart_render(self.payload)
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/helpers/rendering.py", line 123, in _smart_render
    for line in self._get_rendered_results(data):
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/helpers/rendering.py", line 110, in _get_rendered_results
    for sagan in data:
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/helpers/rendering.py", line 59, in __iter__
    for sagan in self._attach_probes(sagans):
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/helpers/rendering.py", line 77, in _attach_probes
    [(p.id, p) for p in Probe.get_many(s.probe_id for s in sagans)]
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/probes/__init__.py", line 55, in get_many
    probe = cache.get("probe:{}".format(pk))
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/cache.py", line 71, in get
    if key in self._db:
  File "/usr/lib/python3.5/site-packages/ripe/atlas/tools/cache.py", line 46, in _db
    self._db_file = dbm.open(self._get_or_create_db_path(), "c")
  File "/usr/lib/python3.5/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable

**Comment by astrikos** [comment]
Hi,
do you still have this issue?
What we do normally is have a cache file either in /tmp or in $HOME/.config/ripe-atlas-tools
Could you see if there is a file in there? and if you can access it what kind of permissions does it have?

**Comment by ghostonthewire** [comment]
I've got nearly the same issue with the exception of different `Errno` on OS X 10.11.6 with Python 3.6.0 (2.7.9 as well). The file is in `$HOME/.config/ripe-atlas-tools`, opened fine (see `lsof` and `ls` outputs within debuger session), and at first yields valid dbm object, but then, while `self._db` property has been accessed, it is trying to open `self._db_file` with following error.

```
% python3 -m pdb =ripe-atlas report 7694542 --renderer traceroute
> /Users/gotw/.virtualenvs/ripeatlas/bin/ripe-atlas(3)<module>()
-> import os
(Pdb) b /Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/cache.py:47
Breakpoint 1 at /Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/cache.py:47
(Pdb) c
> /Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/cache.py(47)_db()
-> return self._db_file
(Pdb) list
 42
 43         @property
 44         def _db(self):
 45             if not self._db_file:
 46                 self._db_file = dbm.open(self._get_or_create_db_path(), "c")
 47 B->         return self._db_file
 48
 49         def __contains__(self, key):
 50             return key in self._db
 51
 52         def __getitem__(self, key):
(Pdb) self._db_file
<_gdbm.gdbm object at 0x108c738f0>
(Pdb) self._db_file['key']
*** KeyError: 'key'

---
% lsof +D ~/.config/ripe-atlas-tools
COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
python3.6 91029 gotw  txt    REG    1,4    12288 40791765 /Users/gotw/.config/ripe-atlas-tools/cache-3.6.0.db
python3.6 91029 gotw    8u   REG    1,4    12288 40791765 /Users/gotw/.config/ripe-atlas-tools/cache-3.6.0.db

% ls -la ~/.config/ripe-atlas-tools/cache-3.6.0.db
-rw-r--r--  1 gotw  staff  12288 Jan 15 23:05 /Users/gotw/.config/ripe-atlas-tools/cache-3.6.0.db
---

(Pdb) c
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/gotw/.virtualenvs/ripeatlas/bin/ripe-atlas", line 151, in <module>
    sys.exit(RipeAtlas().main())
  File "/Users/gotw/.virtualenvs/ripeatlas/bin/ripe-atlas", line 146, in main
    cmd.run()
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/commands/report.py", line 205, in run
    Rendering(renderer=renderer, payload=results).render()
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/helpers/rendering.py", line 100, in render
    self._smart_render(self.payload)
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/helpers/rendering.py", line 123, in _smart_render
    for line in self._get_rendered_results(data):
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/helpers/rendering.py", line 110, in _get_rendered_results
    for sagan in data:
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/helpers/rendering.py", line 65, in __iter__
    for sagan in self._attach_probes(sagans):
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/helpers/rendering.py", line 77, in _attach_probes
    [(p.id, p) for p in Probe.get_many(s.probe_id for s in sagans)]
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/probes/__init__.py", line 55, in get_many
    probe = cache.get("probe:{}".format(pk))
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/cache.py", line 71, in get
    if key in self._db:
  File "/Users/gotw/.virtualenvs/ripeatlas/lib/python3.6/site-packages/ripe/atlas/tools/cache.py", line 46, in _db
    self._db_file = dbm.open(self._get_or_create_db_path(), "c")
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 35] Resource temporarily unavailable
```

**Comment by AlfredArouna** [comment]
@astrikos , excuse for late delay. Still having the same issue. I check it now. This is what i have for your request.
ls -lh  $HOME/.config/ripe-atlas-tools/cache-3.6.0.db
-rw-r--r-- 1 aar aar 12K Mar 29 12:35 /home/user/.config/ripe-atlas-tools/cache-3.6.0.db
