### ISSUE TITLE
KeyError in report --aggregate-by country for a build in measurment

### ISSUE THREAD

**Issue by fobser** [RIPE-NCC/ripe-atlas-tools#184]
$ ripe-atlas report --aggregate-by country 10301
Traceback (most recent call last):
  File "/opt/ripe-atlas-tools/bin/ripe-atlas", line 151, in <module>
    sys.exit(RipeAtlas().main())
  File "/opt/ripe-atlas-tools/bin/ripe-atlas", line 146, in main
    cmd.run()
  File "/opt/ripe-atlas-tools/lib/python2.7/site-packages/ripe/atlas/tools/commands/report.py", line 203, in run
    results = aggregate(results, self.get_aggregators())
  File "/opt/ripe-atlas-tools/lib/python2.7/site-packages/ripe/atlas/tools/aggregators/base.py", line 98, in aggregate
    for entity in entities:
  File "/opt/ripe-atlas-tools/lib/python2.7/site-packages/ripe/atlas/tools/helpers/rendering.py", line 59, in __iter__
    for sagan in self._attach_probes(sagans):
  File "/opt/ripe-atlas-tools/lib/python2.7/site-packages/ripe/atlas/tools/helpers/rendering.py", line 80, in _attach_probes
    sagan.probe = probes[sagan.probe_id]
KeyError: 32401

This is without an api key, the issue might be that the probe 32401 is not public

**Comment by astrikos** [comment]
That was a problem on the backend. We had forgotten to increase a constant which made the system not give you the new probes above 32399. Now that should be fixed. Thanks for the heads up!
