### ISSUE TITLE
Renderer aggregate_ping broken ("TypeError: __init__() got an unexpected keyword argument 'arguments'")

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/ripe-atlas-tools#186]
Tools installed via pip a few minutes ago. This works:

```
% ripe-atlas measure ping --renderer ping --target 2017.rmll.info
```

But this one does not:

```
% ripe-atlas measure ping --renderer aggregate_ping --target 2017.rmll.info  

Looking good!  Your measurement was created and details about it can be found here:

  https://atlas.ripe.net/measurements/9122126/


Connecting to stream...


Disconnecting from stream

You can find details about this measurement here:

  https://atlas.ripe.net/measurements/9122126/

Traceback (most recent call last):
  File "/usr/local/bin/ripe-atlas", line 151, in <module>
    sys.exit(RipeAtlas().main())
  File "/usr/local/bin/ripe-atlas", line 146, in main
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/ripe/atlas/tools/commands/measure/base.py", line 241, in run
    self.stream(pk, url)
  File "/usr/local/lib/python2.7/dist-packages/ripe/atlas/tools/commands/measure/base.py", line 279, in stream
    self.arguments.renderer, self.arguments, self._type, pk)
  File "/usr/local/lib/python2.7/dist-packages/ripe/atlas/tools/streaming.py", line 42, in stream
    arguments=arguments
TypeError: __init__() got an unexpected keyword argument 'arguments'

%  python --version
Python 2.7.13
```

**Comment by chrisamin** [comment]
aggregate_ping will be rolled into ping in the next release (see 5bef4af7c9eddf78e50bf8535144b73659e29650)
