### ISSUE TITLE
ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/ripe-atlas-tools#2]
% ripe-atlas measure ping --target  www.afnic.fr
Traceback (most recent call last):
  File "/home/stephane/.local/bin/ripe-atlas", line 77, in <module>
    sys.exit(RipeAtlas().main())
  File "/home/stephane/.local/bin/ripe-atlas", line 67, in main
    [self.command]
  File "/home/stephane/.local/lib/python2.7/site-packages/ripe/atlas/tools/commands/measure.py", line 5, in <module>
    from ripe.atlas.cousteau import (
  File "/home/stephane/.local/lib/python2.7/site-packages/ripe/atlas/cousteau/__init__.py", line 10, in <module>
    from .stream import AtlasStream
  File "/home/stephane/.local/lib/python2.7/site-packages/ripe/atlas/cousteau/stream.py", line 1, in <module>
    from socketIO_client import SocketIO
  File "/home/stephane/.local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 12, in <module>
    from .transports import (
  File "/home/stephane/.local/lib/python2.7/site-packages/socketIO_client/transports.py", line 1, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 42, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by bortzmeyer** [comment]
Browsing the Web with this error message, it seems a very common problem in Python programs which assume that SSLv3 support is available: it is no longer (see RFC 7568), Debian ships with OpenSSL without the old and insecure protocol SSLv3.

**Comment by astrikos** [comment]
I think your version of requests(2.0) is causing this. According to http://stackoverflow.com/a/29081240 if you update requests above 2.6 it should be fixed. 
A solution would be to enforce this version on setup.py?

**Comment by danielquinn** [comment]
As a short-term fix for this, I've bumped up the requirement in Cousteau to `requests>=2.7.0`.  As this is actually a bug in SocketIO-client's dependencies, I've issued a [pull request](https://github.com/invisibleroads/socketIO-client/issues/92) to them for a related issue.  If someone else can confirm that this goes away with a modern version of `requests`, I'll close this issue.

**Comment by bortzmeyer** [comment]
Indeed. 

sudo pip install --upgrade  requests 

And now, it works.

**Comment by danielquinn** [comment]
Thanks for the test!
