### ISSUE TITLE
Can't run on centos 7

### ISSUE THREAD

**Issue by tamaszl** [RIPE-NCC/ripe-atlas-tools#230]
```
./ripe-atlas
Traceback (most recent call last):
  File "./ripe-atlas", line 8, in <module>
    from ripe.atlas.tools.commands.measure import Factory as BaseFactory
  File "/root/test/lib64/python3.6/site-packages/ripe/atlas/tools/commands/measure/__init__.py", line 20, in <module>
    from .ping import PingMeasureCommand
  File "/root/test/lib64/python3.6/site-packages/ripe/atlas/tools/commands/measure/ping.py", line 18, in <module>
    from ...helpers.validators import ArgumentType
  File "/root/test/lib64/python3.6/site-packages/ripe/atlas/tools/helpers/validators.py", line 25, in <module>
    from ..settings import aliases
  File "/root/test/lib64/python3.6/site-packages/ripe/atlas/tools/settings/__init__.py", line 287, in <module>
    conf = Configuration().get()
  File "/root/test/lib64/python3.6/site-packages/ripe/atlas/tools/settings/__init__.py", line 34, in get
    custom = yaml.load(y)
TypeError: load() missing 1 required positional argument: 'Loader'
```

**Comment by tamaszl** [comment]
If I delete the rc file then ripe-atlas doesn't show this error.

**Comment by tamaszl** [comment]
found solution in https://github.com/RIPE-NCC/ripe-atlas-tools/commit/1134afc0451e97c15053855118515b0d2d1da280
i went to /Users/zeki893/code/ripe-atlas-tools/lib/python3.8/site-packages/ripe/atlas/tools/settings/__init__.py and updated 
                from 
                custom = yaml.load(y)
                to
                custom = yaml.load(y, Loader=yaml.FullLoader)
