### ISSUE TITLE
Crash running measurement

### ISSUE THREAD

**Issue by shane-ns1** [RIPE-NCC/ripe-atlas-tools#242]
The `ripe-atlas` tool crashed while running a measurement. Here's the stack trace:
```
Traceback (most recent call last):
  File "/home/skerr/tmp/ripe-atlas-venv/bin/ripe-atlas", line 151, in <module>
    sys.exit(RipeAtlas().main())
             ^^^^^^^^^^^^^^^^^^
  File "/home/skerr/tmp/ripe-atlas-venv/bin/ripe-atlas", line 146, in main
    cmd.run()
  File "/home/skerr/tmp/ripe-atlas-venv/lib64/python3.11/site-packages/ripe/atlas/tools/commands/measure/base.py", line 314, in run
    self.stream(pk, url)
  File "/home/skerr/tmp/ripe-atlas-venv/lib64/python3.11/site-packages/ripe/atlas/tools/commands/measure/base.py", line 362, in stream
    renderer.render(stream)
  File "/home/skerr/tmp/ripe-atlas-venv/lib64/python3.11/site-packages/ripe/atlas/tools/renderers/base.py", line 196, in render
    for sagan in results:
  File "/home/skerr/tmp/ripe-atlas-venv/lib64/python3.11/site-packages/ripe/atlas/tools/streaming.py", line 45, in __iter__
    for event_name, payload in stream.iter(seconds=self.timeout):
  File "/home/skerr/tmp/ripe-atlas-venv/lib64/python3.11/site-packages/ripe/atlas/cousteau/stream.py", line 210, in iter
    rlist, _, _ = select.select([self.ws], [], [], remaining)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skerr/tmp/ripe-atlas-venv/lib64/python3.11/site-packages/websocket/_core.py", line 116, in fileno
    return self.sock.fileno()
           ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fileno'
```

Here's the measurement ID:
https://atlas.ripe.net/measurements/56348233/

The invocation looked like this:
```
ripe-atlas measure dns \
  --auth REDACTED \
  --from-probes 4958,11918,35561,50200,52008,52867,1003812,6861,17250,25438 \
  --af 4 --udp-payload-size 1232 \
  --query-type NS --query-argument twc-test.natedaly.net
```

It's reproducible from my system using these values. 

If I use a different set of probes it does not crash, so I am guessing there is some issue with one of the probes that confuses `ripe-atlas` somehow.

**Comment by shane-ns1** [comment]
I do notice that there are only 9 probes created in the measurement, although 10 were requested. Maybe `ripe-atlas` timed out waiting on a probe not present in the measurement? :thinking:
