### ISSUE TITLE
Traceback while using 'report'

### ISSUE THREAD

**Issue by spakka** [RIPE-NCC/ripe-atlas-tools#42]
Hiya,

Just updated to the latest git master of ripe-atlas-tools, ripe-atlas-cousteau and ripe.atlas.sagan.
When I run:
```
ripe-atlas report 1001 --renderer raw
```
It dumps out many rows but after about 3300 rows, it dies with a traceback:
```
Traceback (most recent call last):
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/bin/ripe-atlas", line 10, in <module>
    execfile(__file__)
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/scripts/ripe-atlas", line 79, in <module>
    sys.exit(RipeAtlas().main())
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/scripts/ripe-atlas", line 70, in main
    cmd.run()
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/commands/report.py", line 112, in run
    payload=results
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/helpers/rendering.py", line 81, in render
    self._smart_render(self.payload)
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/helpers/rendering.py", line 104, in _smart_render
    for line in self._get_rendered_results(data):
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/helpers/rendering.py", line 86, in _get_rendered_results
    for sagan in data:
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/helpers/rendering.py", line 43, in __iter__
    for sagan in self._attach_probes(sagans):
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/helpers/rendering.py", line 61, in _attach_probes
    [(p.id, p) for p in Probe.get_many(s.probe_id for s in sagans)]
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/probes/__init__.py", line 40, in get_many
    probe = cache.get("probe:{}".format(pk))
  File "/Users/cpetrie/Library/PythonVEs/ripe-atlas-tools/src/ripe.atlas.tools/ripe/atlas/tools/cache.py", line 42, in get
    expires, value = pickle.loads(self._db[key])
AttributeError: 'module' object has no attribute 'Status'
```
Thought I'd let you know :)

Cheers
Colin

**Comment by astrikos** [comment]
okay removing cache seems to has solve this with the current master. Closing for now and if it happens again we reopen it.
